on:
  push:
    branches:
      - "master"
    paths:
      - "CopyDllsAfterBuildLocalTools/**/*"
  pull_request:
    branches:
      - "master"
    paths:
      - "CopyDllsAfterBuildLocalTools/**/*"

env:
  DOTNET_5: 5.0.x
  DOTNET_3: 3.1.x

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_5 }}
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_3 }}
      - run: dotnet build ./CopyDllsAfterBuildLocalTools/CopyDllsAfterBuildLocalTools/ -c Debug
      - run: dotnet test ./CopyDllsAfterBuildLocalTools/CopyDllsAfterBuildLocalToolsUnitTest/ -c Debug
